image: node:6.9.0

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm cache clean
  - npm install hexo-cli -g
  - npm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master